### ISSUE TITLE
Warning using global Ember

### ISSUE THREAD

**Issue by tehmaestro** [sinankeskin/ember-oauther#7]
Hi, on Ember 3.28 this addon throws a warning, which is caused by this https://github.com/emberjs/ember.js/issues/19705
Ember Simple Auth seems to have removed the registration completely https://github.com/mainmatter/ember-simple-auth/issues/2309

Any idea how we can move forward?

**Comment by sinankeskin** [comment]
I'll check ASAP @tehmaestro I think I know how to fix.

**Comment by sinankeskin** [comment]
I've just released v3.0. Please check. Thanks @tehmaestro

**Comment by tehmaestro** [comment]
Thank you, everything is ok now. Love your addon btw, good job.
